---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: numberproperties.domotik8s.io
spec:
  group: domotik8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:

            # SPEC
            spec:
              type: object
              properties:

                # ADDRESS
                address:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    system: 
                      type: string
                    instance: 
                      type: string

                # STATE
                state:
                  type: object
                  properties:
                    value:
                      type: number

                # ACCESS
                access: 
                  type: array
                  items:
                    type: string
                    enum:
                      - READ
                      - WRITE

            # STATUS
            status:
              type: object
              properties:

                # STATE
                state:
                  type: object
                  properties:
                    value:
                      type: number

                # LASTUPDATED
                lastUpdated:
                    type: string
                    format: date-time
  scope: Cluster
  names:
    plural: numberproperties
    singular: numberproperty
    kind: NumberProperty
    shortNames:
      - np
      - nps
