---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: numericsensors.domotik8s.io
spec:
  group: domotik8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                connection:
                  type: object
                  properties:
                    system: 
                      type: string
                    instance: 
                      type: string
                    config:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - system
                  - config
                state:
                  type: object
                  properties:
                    value:
                      type: number
                    unit:
                      type: string
            status:
              type: object
              properties:
                state:          
                  type: object
                  properties:
                    value:
                      type: number
                    unit:
                      type: string
                lastUpdated:
                    type: string
                    format: date-time
  scope: Cluster
  names:
    plural: numericsensors
    singular: numericsensor
    kind: NumericSensor
    shortNames: []
