apiVersion: domotik8s.io/v1beta1
kind: NumberProperty
metadata:
  name: guest-bathroom-temperature
  labels:
    area: "House"
    floor: "FirstFloor"
    room: "GuestBathRoom"
    name: "Temperature"
spec:
  address:
    system: "knx"
    read: "2/0/0"
    dpt: "9.001"
