apiVersion: domotik8s.io/v1beta1
kind: BooleanProperty
metadata:
  name: office-window-right
  labels:
    area: "House"
    floor: "FirstFloor"
    room: "Office"
    name: "WindowRight"
spec:
  address:
    system: "knx"
    read: "3/1/5"
    dpt: "1.018"
